export interface DefaultOpportunity {
  name: string
  program: string
  stage: string
  category: string
  reports_to: string | null
  terms: string | null
  pg_required: string
  description: string | null
  learn_more_url: string | null
  apply_url: string | null
  priority_score: number
  is_active: boolean
  notes: string | null
}

// ─── Program A — 0% APR Card Strategy ────────────────────────────────────────
const PROGRAM_A: DefaultOpportunity[] = [

  // ── Credit Readiness Stage ──
  {
    name: 'Experian Boost',
    program: 'program_a',
    stage: 'Credit Readiness',
    category: 'monitoring',
    reports_to: 'Experian',
    terms: 'Free',
    pg_required: 'n/a',
    description: 'Add utility, phone, and streaming payments to your Experian personal credit file. Can raise your FICO score by up to 10–20 points instantly. Personal credit tool only — does not create a business tradeline.',
    learn_more_url: 'https://www.experian.com/credit/score-boost/',
    apply_url: 'https://www.experian.com/credit/score-boost/',
    priority_score: 95,
    is_active: true,
    notes: 'Start here — free and immediate personal credit impact. Requires linking eligible bill-pay accounts (utilities, cell phone, streaming).',
  },
  {
    name: 'Self Credit Builder Account',
    program: 'program_a',
    stage: 'Credit Readiness',
    category: 'funding',
    reports_to: 'Equifax, Experian, TransUnion',
    terms: '$25–$150/month, 12–24 month term',
    pg_required: 'n/a',
    description: 'A personal credit-builder loan that reports monthly payments to all 3 personal bureaus. Ideal for thin personal credit files before applying for 0% APR business cards. Funds held in savings account and released when paid off.',
    learn_more_url: 'https://www.self.inc',
    apply_url: 'https://www.self.inc',
    priority_score: 80,
    is_active: true,
    notes: 'Personal credit tool only — not a business account. No hard credit check for approval. Use to add personal payment history before card applications.',
  },
  {
    name: 'Secured Discover it® Card',
    program: 'program_a',
    stage: 'Credit Readiness',
    category: 'funding',
    reports_to: 'Equifax, Experian, TransUnion',
    terms: '$200 minimum deposit, no annual fee',
    pg_required: 'yes',
    description: 'A secured personal card that graduates to unsecured after ~7 months of on-time payments. Reports to all 3 personal bureaus. Good stepping stone for those under 640 FICO before applying for 0% APR business cards.',
    learn_more_url: 'https://www.discover.com/credit-cards/secured-credit-card/',
    apply_url: 'https://www.discover.com/credit-cards/secured-credit-card/',
    priority_score: 75,
    is_active: true,
    notes: 'Use if personal FICO is below 640. Graduation to unsecured is common but not guaranteed. Personal card only.',
  },

  // ── Application Strategy Stage ──
  {
    name: 'Chase Ink Business Unlimited®',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Experian Business, Equifax Business',
    terms: '0% intro APR 12 months, unlimited 1.5% cash back, no annual fee',
    pg_required: 'yes',
    description: 'One of the top 0% intro APR business cards. No annual fee and unlimited 1.5% cash back. Reports to Experian Business and Equifax Business via SBFE. Ideal first business card in the Program A stack.',
    learn_more_url: 'https://creditcards.chase.com/business-credit-cards/ink/unlimited',
    apply_url: 'https://creditcards.chase.com/business-credit-cards/ink/unlimited',
    priority_score: 98,
    is_active: true,
    notes: 'Apply first — typically highest approval odds. Reports to business bureaus via SBFE. Requires good to excellent personal credit (670+). No EIN strictly required for sole props.',
  },
  {
    name: 'Chase Ink Business Cash®',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Experian Business, Equifax Business',
    terms: '0% intro APR 12 months, 5% on office/internet, no annual fee',
    pg_required: 'yes',
    description: 'Pairs with Chase Ink Unlimited for category-specific spending. 5% back at office stores and on internet/cable/phone (capped annually). Reports to Experian Business and Equifax Business via SBFE. No annual fee.',
    learn_more_url: 'https://creditcards.chase.com/business-credit-cards/ink/cash',
    apply_url: 'https://creditcards.chase.com/business-credit-cards/ink/cash',
    priority_score: 95,
    is_active: true,
    notes: 'Apply same day or within 2 days of Ink Unlimited. Reports to business bureaus via SBFE.',
  },
  {
    name: 'U.S. Bank Business Triple Cash Rewards Visa®',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Dun & Bradstreet',
    terms: '0% intro APR 12 billing cycles, 3% cash back on eligible purchases, no annual fee',
    pg_required: 'yes',
    description: 'Strong 0% APR period at 12 billing cycles. 3% back on eligible business categories. Reports to D&B. No annual fee. Good for clients who want a longer interest-free window.',
    learn_more_url: 'https://www.usbank.com/business-banking/business-credit-cards/business-triple-cash-back-credit-card.html',
    apply_url: 'https://www.usbank.com/business-banking/business-credit-cards/business-triple-cash-back-credit-card.html',
    priority_score: 90,
    is_active: true,
    notes: 'Reports to D&B via SBFE. Requires good to excellent personal credit (670+). Apply after Chase cards.',
  },
  {
    name: 'Bank of America Business Advantage Unlimited Cash',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Dun & Bradstreet, Equifax Business',
    terms: '0% intro APR 7 billing cycles, unlimited 1.5% cash back, no annual fee',
    pg_required: 'yes',
    description: 'Good addition to the 0% APR stack. Reports to D&B and Equifax Business via SBFE. Preferred Rewards members get higher cash back rates. No annual fee.',
    learn_more_url: 'https://www.bankofamerica.com/smallbusiness/credit-cards/products/unlimited-cash-rewards-business-credit-card/',
    apply_url: 'https://www.bankofamerica.com/smallbusiness/credit-cards/products/unlimited-cash-rewards-business-credit-card/',
    priority_score: 82,
    is_active: true,
    notes: 'Reports to D&B and Equifax Business via SBFE. Bonus if client has existing BofA accounts. 0% intro APR is 7 billing cycles (not 9 — updated).',
  },
  {
    name: 'Capital One Spark Cash Plus',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'No preset spending limit, 2% unlimited cash back, $150 annual fee',
    pg_required: 'yes',
    description: 'Charge card with no preset spending limit — useful for high-spend months without utilization impact. 2% unlimited cash back. Full tri-bureau business reporting. Does NOT report to personal bureaus unless delinquent.',
    learn_more_url: 'https://www.capitalone.com/small-business/credit-cards/spark-cash-plus/',
    apply_url: 'https://www.capitalone.com/small-business/credit-cards/spark-cash-plus/',
    priority_score: 78,
    is_active: true,
    notes: 'Notable: does not report to personal bureaus unless delinquent — only reports to business bureaus. Charge card — balance must be paid in full monthly. $150K+ annual spend earns annual fee rebate.',
  },

  // ── Card Acquisition Stage ──
  {
    name: 'American Express Blue Business Cash™',
    program: 'program_a',
    stage: 'Card Acquisition',
    category: 'funding',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: '0% intro APR 12 months on purchases, 2% cash back up to $50K/year, no annual fee',
    pg_required: 'yes',
    description: 'Amex business card with 12 months 0% APR and 2% cash back (up to $50K/year). Reports to all three major business bureaus. Amex tends to approve higher limits.',
    learn_more_url: 'https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-blue-business-cash-credit-card/',
    apply_url: 'https://www.americanexpress.com/en-us/campaigns/small-business/credit-cards/blue-business-cash/explore-now/',
    priority_score: 88,
    is_active: true,
    notes: 'Reports to D&B, Experian Business, and Equifax Business. Apply in Card Acquisition phase. Amex allows multiple business cards simultaneously.',
  },
  {
    name: 'American Express Blue Business Plus®',
    program: 'program_a',
    stage: 'Card Acquisition',
    category: 'funding',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: '0% intro APR 12 months, 2x Membership Rewards on first $50K, no annual fee',
    pg_required: 'yes',
    description: 'Earns 2x Membership Rewards points instead of cash back. Ideal if client also has an Amex personal card to transfer points. Reports to all three major business bureaus.',
    learn_more_url: 'https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-blue-business-plus-credit-card/',
    apply_url: 'https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-blue-business-plus-credit-card/',
    priority_score: 85,
    is_active: true,
    notes: 'Reports to D&B, Experian Business, and Equifax Business. Can apply alongside Blue Business Cash — Amex allows multiple cards.',
  },
  {
    name: 'Wells Fargo Business Platinum Credit Card',
    program: 'program_a',
    stage: 'Card Acquisition',
    category: 'funding',
    reports_to: null,
    terms: 'No longer available for new applicants',
    pg_required: 'yes',
    description: 'DISCONTINUED — Wells Fargo Business Platinum has been removed from consumer-facing acquisition funnels and is no longer available for new applicants.',
    learn_more_url: 'https://creditcards.wellsfargo.com',
    apply_url: null,
    priority_score: 0,
    is_active: false,
    notes: 'DISCONTINUED — product removed from Wells Fargo active lineup. Direct clients to current Wells Fargo business card offerings at creditcards.wellsfargo.com',
  },

  // ── Optimization Stage ──
  {
    name: 'Nav Business Credit Monitoring',
    program: 'program_a',
    stage: 'Optimization',
    category: 'monitoring',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Free / ~$29.99/month (Manager) / ~$39.99/month (Business Boost)',
    pg_required: 'n/a',
    description: 'Tracks personal and business credit scores across all major bureaus. The Business Boost tier reports your subscription as a tradeline to business bureaus. Includes D&B, Experian Intelliscore, and Equifax Business score visibility.',
    learn_more_url: 'https://www.nav.com',
    apply_url: 'https://www.nav.com/pricing/',
    priority_score: 80,
    is_active: true,
    notes: 'Business Boost (~$39.99/month) is the tier that creates a reporting tradeline to business bureaus. Free tier offers basic letter-grade insights. Confirm which scores are visible on current plan inside Nav dashboard.',
  },
]

// ─── Program B — Business Credit Builder ─────────────────────────────────────
const PROGRAM_B: DefaultOpportunity[] = [

  // ── Foundation Stage ──
  {
    name: 'Dun & Bradstreet D-U-N-S Registration',
    program: 'program_b',
    stage: 'Foundation',
    category: 'monitoring',
    reports_to: 'Dun & Bradstreet',
    terms: 'Free (paid expedite available)',
    pg_required: 'n/a',
    description: 'Register for a free D-U-N-S number — the foundation of business credit. Required before most vendor and net-term accounts will report to D&B. Free issuance takes ~30 days; paid expedite available in as few as 5 business days.',
    learn_more_url: 'https://www.dnb.com/duns-number.html',
    apply_url: 'https://www.dnb.com/en-us/smb/duns/get-a-duns.html',
    priority_score: 100,
    is_active: true,
    notes: 'Must be completed first — all D&B vendor accounts depend on D-U-N-S existing. D&B will upsell paid credit and monitoring products — free registration is sufficient for credit building.',
  },
  {
    name: 'Experian Business Credit Profile',
    program: 'program_b',
    stage: 'Foundation',
    category: 'monitoring',
    reports_to: 'Experian Business',
    terms: 'Free to establish',
    pg_required: 'n/a',
    description: 'Set up and monitor your Experian Business credit profile. Search for your business using Experian\'s free lookup tool; if not found, submit a request for Experian to establish a profile. EIN is essential. Many lenders use Experian Business to assess creditworthiness.',
    learn_more_url: 'https://www.experian.com/small-business/business-credit-report.jsp',
    apply_url: 'https://www.experian.com/small-business/establish-business-credit',
    priority_score: 90,
    is_active: true,
    notes: 'Monitor monthly as accounts are added. EIN strongly recommended. D-U-N-S not required by Experian — they use their own identifiers.',
  },
  {
    name: 'Equifax Small Business Credit Monitor',
    program: 'program_b',
    stage: 'Foundation',
    category: 'monitoring',
    reports_to: 'Equifax Business',
    terms: '~$16.95–$29.95/month (verify current pricing directly with Equifax)',
    pg_required: 'n/a',
    description: 'Monitor your Equifax business credit file and receive alerts on new reporting activity. Product name and pricing have changed from legacy $14.95/month — verify current plan options directly with Equifax before recommending a specific tier.',
    learn_more_url: 'https://www.equifax.com/business/products/',
    apply_url: 'https://www.equifax.com/business/products/',
    priority_score: 85,
    is_active: true,
    notes: 'PRICING OUTDATED — legacy $14.95/month no longer confirmed. Current plans run ~$16.95–$29.95+. Verify directly with Equifax for current product name and pricing before client recommendation.',
  },
  {
    name: 'eCredable Business Lift',
    program: 'program_b',
    stage: 'Foundation',
    category: 'monitoring',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Paid Business Lift subscription (free tier discontinued)',
    pg_required: 'no',
    description: 'eCredable reports your existing business utility, phone, internet, and service payments to D&B, Experian Business, and Equifax Business. A fast way to add reporting tradelines without opening new credit accounts. Can report up to 24 months of payment history to Equifax Business.',
    learn_more_url: 'https://ecredable.com/products/ecredable-business-lift',
    apply_url: 'https://ecredable.com/products/ecredable-business-lift',
    priority_score: 82,
    is_active: true,
    notes: 'Tri-bureau reporting confirmed by eCredable directly. Free basic tier is discontinued — current model is paid Business Lift subscriptions only. EIN effectively required to match business to bureaus. Business bank account needed to verify eligible utility/service accounts.',
  },

  // ── Store Credit Stage ──
  {
    name: 'Uline Net 30 Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Net 30 payment terms',
    pg_required: 'varies',
    description: 'Uline is one of the most reliable vendor tradelines for business credit building. Purchase shipping and office supplies to establish net-30 payment history. Tri-bureau reporting to D&B, Experian Business, and Equifax Business. Minimum ~$50 order recommended for reporting to trigger.',
    learn_more_url: 'https://www.uline.com',
    apply_url: 'https://www.uline.com',
    priority_score: 98,
    is_active: true,
    notes: 'No separate credit application URL — create a business account at uline.com, then request net-30 billing at checkout or via customer service. PG varies: most established businesses approved without PG; very new/thin-file businesses may be asked to prepay initially. EIN required.',
  },
  {
    name: 'Quill.com Net 30 Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30 payment terms, ~$100 minimum first order',
    pg_required: 'varies',
    description: 'Office supply vendor reporting to D&B and Experian Business. Apply for net-30 terms at checkout by selecting "Apply for Net 30 Terms" as the payment method. Minimum first order ~$100. EIN required.',
    learn_more_url: 'https://www.quill.com',
    apply_url: 'https://www.quill.com',
    priority_score: 93,
    is_active: true,
    notes: 'Application happens at checkout — no separate apply URL. PG varies: accessible to newer businesses, but thin-file applicants may need to prepay initially. EIN required. Equifax Business reporting less consistent than D&B and Experian.',
  },
  {
    name: 'Grainger Net 30 Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms, ~$50 minimum order for D&B reporting',
    pg_required: 'no',
    description: 'Industrial supply company with confirmed D&B reporting. D-U-N-S number and EIN required. Minimum ~$50 order for the invoice to report to D&B. Starting credit limit typically around $1,000 with increases to $5,000+ available.',
    learn_more_url: 'https://www.grainger.com',
    apply_url: 'https://www.grainger.com/content/small-business-center',
    priority_score: 88,
    is_active: true,
    notes: 'D-U-N-S required — must have existing D&B file. EIN required. Business bank account expected. 3+ months in business preferred. Best for businesses that can justify industrial/MRO purchases.',
  },
  {
    name: 'Amazon Business Prime — Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: null,
    terms: 'Net 30 via Pay by Invoice, $179/year Prime membership',
    pg_required: 'varies',
    description: 'REMOVED AS TRADELINE — Amazon Business Pay by Invoice does not currently report to any major business credit bureau (D&B, Experian Business, or Equifax Business). Do not count toward bureau-building progress.',
    learn_more_url: 'https://business.amazon.com',
    apply_url: null,
    priority_score: 0,
    is_active: false,
    notes: 'REMOVED — Confirmed by multiple sources that Amazon Pay by Invoice does not report to business credit bureaus. Removed from active program recommendations.',
  },
  {
    name: 'Summa Office Supplies Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30, $75 annual fee',
    pg_required: 'no',
    description: 'Starter-friendly vendor with low order minimums. Reports to D&B. $75 annual fee. Ideal for businesses needing an accessible early-stage D&B tradeline.',
    learn_more_url: 'https://www.summaofficesupplies.com',
    apply_url: 'https://www.summaofficesupplies.com',
    priority_score: 85,
    is_active: true,
    notes: 'Reports to D&B only — Experian Business reporting not confirmed. $75 annual fee required. EIN required. Low barrier to entry.',
  },
  {
    name: 'Crown Office Supplies Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Net 30, ~$99 annual membership fee',
    pg_required: 'no',
    description: 'Tri-bureau net-30 vendor reporting to D&B, Experian Business, and Equifax Business. Annual membership fee itself is reported as a tradeline. Offers a wide catalog of office supplies and business essentials. Startup-friendly.',
    learn_more_url: 'https://www.crownofficesupplies.com',
    apply_url: 'https://crownofficesupplies.com/net30-application/',
    priority_score: 80,
    is_active: true,
    notes: 'Tri-bureau reporting confirmed. ~$99 annual membership fee. EIN required. Also reports to Creditsafe and NACM per older program descriptions.',
  },
  {
    name: 'Pilot Flying J Business Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Net 30 or Net 15 payment terms',
    pg_required: 'varies',
    description: 'Pilot Flying J business/fleet accounts cover fuel and travel center purchases. Reports to D&B, Experian Business, and Equifax Business. Some no-PG options available for qualified fleet operators. Primarily serves transportation and trucking businesses.',
    learn_more_url: 'https://www.pilotflyingj.com',
    apply_url: 'https://www.pilotflyingj.com',
    priority_score: 74,
    is_active: true,
    notes: 'Tri-bureau reporting confirmed. PG varies — no-PG options exist for qualified fleets; newer businesses may require PG or credit review. Best for businesses with active transportation or fleet operations. EIN and business bank account required. Verify current fleet card application path on live site.',
  },
  {
    name: 'Wilmar Industries Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Experian Business',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Wilmar distributes maintenance, repair, and janitorial supplies primarily to the apartment housing and property management industry. Business net-30 accounts report to Experian Business. At least 1 year in business required.',
    learn_more_url: 'https://www.wilmar.com',
    apply_url: 'https://www.wilmar.com',
    priority_score: 72,
    is_active: true,
    notes: 'Experian Business reporting confirmed. 1 year in business required. D-U-N-S required. EIN required. Business bank account required. No virtual addresses accepted. Credit application submitted via email/upload — navigate to credit page on wilmar.com. Industry focus: apartment housing, property management, facilities maintenance.',
  },
  {
    name: 'The CEO Creative Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Net 30, ~$49 annual membership fee, up to ~$5,500 credit line',
    pg_required: 'no',
    description: 'Tri-bureau net-30 vendor explicitly confirming no personal guarantee. Offers branded merchandise, apparel, office and tech products, plus creative services. Annual membership fee. Up to ~$5,500 credit line. Startup-friendly.',
    learn_more_url: 'https://theceocreative.com',
    apply_url: 'https://theceocreative.com/business-net-30-account/',
    priority_score: 74,
    is_active: true,
    notes: 'Tri-bureau reporting confirmed by vendor (D&B + Equifax minimum; Experian also referenced in their content). No PG confirmed by vendor. ~$49 annual fee. EIN required.',
  },
  {
    name: 'Shirtsy Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Net 30 payment terms, lines starting ~$2,000+',
    pg_required: 'varies',
    description: 'Custom branded apparel and promotional products on net-30 terms. Reports to D&B, Experian Business, Equifax Business, and Creditsafe. Lines commonly start around $2,000+ and increase with history. Startup-friendly.',
    learn_more_url: 'https://shirtsy.com',
    apply_url: 'https://shirtsy.com',
    priority_score: 72,
    is_active: true,
    notes: 'Tri-bureau + Creditsafe reporting confirmed. PG varies — generally no hard personal pull for starter limits but may tighten for very thin files. EIN required. Net-30 application flow via site registration.',
  },
  {
    name: 'Creative Analytics DC Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Equifax Business, Creditsafe',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Business services vendor offering digital marketing, website design, and marketing campaign services on net-30 terms. Reports to Equifax Business and Creditsafe — useful for adding Equifax-specific coverage.',
    learn_more_url: 'https://creativeanalyticsdc.com',
    apply_url: 'https://creativeanalyticsdc.com',
    priority_score: 66,
    is_active: true,
    notes: 'Equifax Business and Creditsafe reporting confirmed by vendor marketing. No PG. EIN required. Bureau reporting has been questioned by some independent reviewers — recommend monitoring live tradeline after opening.',
  },
  {
    name: 'Wise Business Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'cash',
    reports_to: null,
    terms: 'Free to open; pay-as-you-go transaction fees',
    pg_required: 'no',
    description: 'REMOVED AS TRADELINE — Wise Business is a payments and banking platform, not a credit provider. Confirmed does NOT report account activity as a business credit tradeline to D&B, Experian Business, or Equifax Business.',
    learn_more_url: 'https://wise.com/business',
    apply_url: null,
    priority_score: 0,
    is_active: false,
    notes: 'REMOVED — Wise Business confirmed as payments platform only. Does not report to business credit bureaus. Removed from active program recommendations.',
  },
  {
    name: 'Zoro Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms, ~$50 minimum purchase, ~$2,500 recommended starting limit',
    pg_required: 'varies',
    description: 'Zoro (a W.W. Grainger company) sells industrial tools, safety equipment, and MRO supplies. Business net-30 accounts report to D&B. Request ~$2,500 starting limit and pay invoices 7–10 days early for best reporting results.',
    learn_more_url: 'https://www.zoro.com',
    apply_url: 'https://www.zoro.com/sign-in/register/business/',
    priority_score: 76,
    is_active: true,
    notes: 'D&B reporting confirmed. PG varies — starter approvals generally no PG but can tighten for weak files. D-U-N-S effectively required — match application details exactly to D&B file. EIN required. Register at /sign-in/register/business/ and apply for net-30 immediately (do not skip that page). Min ~$50 purchase.',
  },
  {
    name: 'DigiKey Business Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: null,
    terms: 'Net 30 payment terms',
    pg_required: 'varies',
    description: 'REMOVED — No consistent evidence that DigiKey business net-30 accounts report to D&B or any major business credit bureau. Cannot be recommended as a business tradeline builder.',
    learn_more_url: 'https://www.digikey.com',
    apply_url: null,
    priority_score: 0,
    is_active: false,
    notes: 'REMOVED — Multiple sources were unable to confirm DigiKey reports to any business credit bureau. Removed from active program recommendations.',
  },
  {
    name: 'CDW Business Credit Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'CDW offers IT products and technology solutions on business net-30 credit. Reports to D&B. Advanced vendor requiring at least 2 years in business and a D&B PAYDEX score of 80+. Not a first-trade vendor.',
    learn_more_url: 'https://www.cdw.com',
    apply_url: 'https://www.cdw.com/webcontent/inside/service/corporate_acct.aspx',
    priority_score: 72,
    is_active: true,
    notes: 'D&B reporting confirmed. ADVANCED VENDOR — requires 2+ years in business and PAYDEX 80+. D-U-N-S required. EIN required. Business bank account required. Download and submit credit application from apply URL. Not appropriate for clients in early Store Credit stage.',
  },
  {
    name: 'Graybar Business Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'varies',
    description: 'Graybar distributes electrical, communications, and data networking products. Business net-30 accounts report to D&B. Best for construction, electrical, or facilities businesses. Prefers established businesses — not a first-trade vendor.',
    learn_more_url: 'https://www.graybar.com',
    apply_url: 'https://www.graybar.com',
    priority_score: 70,
    is_active: true,
    notes: 'D&B reporting confirmed. PG varies — strong established firms approved without PG; smaller/newer businesses may be asked for additional assurance. D-U-N-S required. EIN required. Bank references required. Navigate to credit application on graybar.com.',
  },
  {
    name: 'Tiger Direct Business Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: null,
    terms: 'No longer available',
    pg_required: 'n/a',
    description: 'DISCONTINUED — TigerDirect went through major restructuring and no longer offers an active business net-30 credit account program. No current equivalent.',
    learn_more_url: null,
    apply_url: null,
    priority_score: 0,
    is_active: false,
    notes: 'DISCONTINUED — No reliable current evidence of active business credit account program. Removed from all client recommendations.',
  },
  {
    name: 'Office Depot Business Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'varies',
    description: 'Office Depot business credit account (Citibank-issued) reports to D&B. Provides net-30 terms and revolving business cards for office supplies, furniture, and technology. PG varies based on business strength.',
    learn_more_url: 'https://www.officedepot.com',
    apply_url: 'https://www.officedepot.com/specialLinks.do?file=%2Fcreditcard%2Fbusiness_info.jsp',
    priority_score: 74,
    is_active: true,
    notes: 'Reports to D&B only — Experian Business and Equifax Business reporting not confirmed (previous tri-bureau claim corrected). PG varies — Citibank underwriting; smaller/younger businesses likely require PG or credit check. EIN required.',
  },
  {
    name: 'Staples Business Credit Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'varies',
    description: 'Staples business credit accounts report to D&B. Net-30 terms for office supplies, printing, and workplace goods. Apply via business account form — a rep contacts you to finalize terms.',
    learn_more_url: 'https://www.staples.com',
    apply_url: 'https://www.staples.com',
    priority_score: 75,
    is_active: true,
    notes: 'Reports to D&B only — Experian Business and Equifax Business reporting not confirmed (previous tri-bureau claim corrected). PG varies — case-by-case depending on business strength. EIN required. Annual revenue and estimated monthly spend must be provided.',
  },
  {
    name: "Lowe's Business Credit",
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30 (Commercial Account) or revolving (Business Card)',
    pg_required: 'yes',
    description: "Lowe's Commercial Account (net-30) reports to D&B and Experian Business. Strong tradeline for construction, property management, and home services businesses. Issuer transitioning from Amex to Synchrony as of April 2026.",
    learn_more_url: 'https://www.lowes.com/l/Credit/business-credit-center',
    apply_url: 'https://www.lowes.com/l/Credit/business-credit-center',
    priority_score: 78,
    is_active: true,
    notes: 'Reports to D&B and Experian Business — Equifax Business reporting not confirmed (previous tri-bureau claim corrected). PG required. EIN + SSN of guarantor required. ISSUER UPDATE: Lowe\'s Business Rewards transitioning from Amex to Synchrony as of April 2026 — verify current issuer at time of application.',
  },

  // ── Store Credit Stage — New Additions ──
  {
    name: 'NAMYNOT Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30, ~$89.99/year membership, up to $10,000 tradeline',
    pg_required: 'no',
    description: 'Digital marketing services vendor offering net-30 accounts that report to D&B and Experian Business. Up to $10,000 tradeline. ~$89.99/year membership. Minimum initial deposit of 50% on all orders until 5 on-time payments are established.',
    learn_more_url: 'https://namynot.com',
    apply_url: 'https://namynot.com/net-30/business-credit-application/',
    priority_score: 74,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed by vendor. No PG. EIN required. ~$89.99/year membership fee. 50% upfront deposit required on first 5 orders; terms improve with payment history. Typical approval 1–3 business days.',
  },
  {
    name: 'Wise Business Plans Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Experian Business, Equifax Business, Creditsafe',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Business plans, compliance support, digital marketing, and website design services on net-30 terms. Reports to Experian Business, Equifax Business, and Creditsafe — strong multi-bureau coverage for service-based spending. EIN required.',
    learn_more_url: 'https://www.wisebusinessplans.com',
    apply_url: 'https://www.wisebusinessplans.com',
    priority_score: 73,
    is_active: true,
    notes: 'NOTE: This is Wise Business Plans (wisebusinessplans.com) — completely different from Wise Business Account (wise.com), which was removed. Reports to Experian Business, Equifax Business, and Creditsafe. No PG. EIN required. Fees and minimum spend apply.',
  },
  {
    name: 'Business T-Shirt Club Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Equifax Business, Creditsafe',
    terms: 'Net 30, membership required, $250+ min (blank apparel) or $100+ (pre-designed)',
    pg_required: 'no',
    description: 'Custom apparel and branded merchandise on net-30 terms. Reports to Equifax Business and Creditsafe. Useful specifically for adding an Equifax Business tradeline. 50% upfront payment required initially until track record is established.',
    learn_more_url: 'https://businesstshirtclub.com',
    apply_url: 'https://businesstshirtclub.com',
    priority_score: 65,
    is_active: true,
    notes: 'Reports to Equifax Business and Creditsafe. No PG. EIN required. Membership fee required (amount not fixed in public sources). Min purchase: $250+ for blank apparel, 12 items per design for custom, or $100+ pre-designed. 50% upfront initially until history established.',
  },
  {
    name: 'Northern Tool Commercial Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Net 30 payment terms (via TreviPay)',
    pg_required: 'no',
    description: 'Northern Tool commercial credit account for tools, generators, and industrial equipment. Net-30 terms powered by TreviPay. Reports to business bureaus via TreviPay partnership. No-PG options available for established entities.',
    learn_more_url: 'https://www.northerntool.com',
    apply_url: 'https://www.northerntool.com',
    priority_score: 70,
    is_active: true,
    notes: 'Bureau reporting via TreviPay commercial credit platform. Navigate to Business Solutions / Commercial Account section on northerntool.com to apply. EIN required. Best for businesses needing tools, equipment, or industrial supplies.',
  },
  {
    name: 'Strategic Network Solutions Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Experian Business, Creditsafe',
    terms: 'Net 30, ~$60 minimum initial purchase to trigger reporting',
    pg_required: 'no',
    description: 'IT services, computer accessories, and downloadable digital products on net-30 terms. Reports to Experian Business and Creditsafe. Minimum ~$60 initial purchase required for reporting to trigger. No PG.',
    learn_more_url: 'https://www.strategicnetworksolutions.net',
    apply_url: 'https://www.strategicnetworksolutions.net',
    priority_score: 68,
    is_active: true,
    notes: 'Reports to Experian Business and Creditsafe. No PG. EIN required. Minimum ~$60 initial purchase to trigger tradeline reporting. Verify current URL and apply path on live site.',
  },
  {
    name: 'Ohana Office Products Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Office supplies and electronics vendor offering net-30 accounts that report to D&B. Startup-friendly with no PG for starter accounts. Good entry-level D&B tradeline.',
    learn_more_url: 'https://ohanaofficeproducts.com',
    apply_url: 'https://ohanaofficeproducts.com',
    priority_score: 71,
    is_active: true,
    notes: 'D&B reporting confirmed. No PG for typical starter accounts. EIN required.',
  },
  {
    name: 'Burstbiz Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Digital marketing services, logo design, and website development on net-30 terms. Reports to D&B and Experian Business. No PG. Service-based vendor useful for businesses needing marketing support while building credit.',
    learn_more_url: 'https://burstbiz.com',
    apply_url: 'https://burstbiz.com',
    priority_score: 70,
    is_active: true,
    notes: 'Reports to D&B and Experian Business. No PG. EIN required. Verify current apply URL on live site.',
  },
  {
    name: 'The Red Spectrum Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Business-building services including web design, logo design, and business branding on net-30 terms. Reports to major business bureaus. No PG. Good for early-stage businesses needing marketing assets and credit building simultaneously.',
    learn_more_url: 'https://www.theredspectrum.com',
    apply_url: 'https://www.theredspectrum.com',
    priority_score: 65,
    is_active: true,
    notes: 'Reports to major business bureaus (D&B and Experian Business cited). No PG. EIN required. Verify specific bureaus and apply path on live site.',
  },
  {
    name: 'HD Supply Commercial Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'HD Supply is a wholesale distributor for maintenance, repair, and operations (MRO) supplies. Commercial net-30 accounts report to D&B. No PG typically required for commercial entities. Ideal for property management, hospitality, and facilities businesses.',
    learn_more_url: 'https://www.hdsupply.com',
    apply_url: 'https://www.hdsupply.com',
    priority_score: 73,
    is_active: true,
    notes: 'D&B reporting confirmed. No PG for commercial entities. EIN required. Navigate to credit application on hdsupply.com. Best for property management, hospitality, or facilities management businesses.',
  },
  {
    name: 'Newegg Business Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Equifax Business',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Newegg Business offers electronics, IT hardware, and office technology on net-30 terms. Reports to Equifax Business — adds an Equifax-specific tradeline for tech-oriented businesses. No PG.',
    learn_more_url: 'https://www.neweggbusiness.com',
    apply_url: 'https://www.neweggbusiness.com',
    priority_score: 68,
    is_active: true,
    notes: 'Reports to Equifax Business. No PG. EIN required. Best for businesses purchasing electronics, IT hardware, or computer equipment.',
  },
  {
    name: 'Tractor Supply Co. Business Credit Card',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Experian Business, Equifax Business',
    terms: 'Revolving credit, Citi Retail Services issued',
    pg_required: 'no',
    description: 'Tractor Supply Co. business revolving credit card (Citi Retail Services) reports to Experian Business and Equifax Business. No-PG options available. Great for agricultural, ranch, home improvement, and rural business clients.',
    learn_more_url: 'https://www.tractorsupply.com/tsc/content/business-credit-card',
    apply_url: 'https://www.tractorsupply.com/tsc/content/business-credit-card',
    priority_score: 76,
    is_active: true,
    notes: 'Experian Business + Equifax Business dual-bureau confirmed (Citi Retail Services). No-PG options available. EIN required. Best for agricultural, construction, property, or rural operations businesses.',
  },
  {
    name: 'Advance Auto Parts Commercial Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30 commercial account terms',
    pg_required: 'no',
    description: 'Advance Auto Parts commercial net-30 account for auto parts and vehicle maintenance. Reports to D&B and Experian Business. No PG for professional commercial accounts. Useful for businesses with fleets, transportation, or vehicle maintenance needs.',
    learn_more_url: 'https://www.advanceautoparts.com/en/commercial',
    apply_url: 'https://www.advanceautoparts.com/en/commercial',
    priority_score: 73,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed. No PG for professional accounts. EIN required. Best for transportation, fleet, auto repair, or any business with regular vehicle maintenance needs.',
  },
  {
    name: 'Sherwin-Williams PRO Commercial Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Monthly or Net 30 billing',
    pg_required: 'varies',
    description: 'Sherwin-Williams PRO commercial account for paint and industrial coatings. Reports to D&B and Experian Business. Monthly or net-30 billing options. Best for construction, painting, property management, or facilities businesses.',
    learn_more_url: 'https://pro.sherwin-williams.com',
    apply_url: 'https://pro.sherwin-williams.com',
    priority_score: 71,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed. PG varies — commercial accounts often available without PG for established businesses. EIN required. Best for construction, painting contractors, or property management.',
  },

  // ── Store Credit Stage — Niche Industry Additions ──
  {
    name: 'Medical Supply Group Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Experian Business',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Medical supply and healthcare equipment vendor offering net-30 business accounts. Reports to Experian Business. No PG. Ideal for healthcare practices, medical businesses, and any business needing medical/lab supplies with credit-building benefits.',
    learn_more_url: 'https://www.medicalsupplygroup.com',
    apply_url: 'https://www.medicalsupplygroup.com',
    priority_score: 68,
    is_active: true,
    notes: 'Experian Business reporting confirmed. No PG. EIN required. Best for medical, healthcare, dental, or lab businesses. Verify current apply URL on live site.',
  },
  {
    name: 'Enerspect Medical Solutions Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Medical equipment and supply vendor offering net-30 tradeline accounts that report to D&B. No PG. Useful for healthcare and medical businesses seeking an early-stage D&B PAYDEX tradeline.',
    learn_more_url: 'https://www.enerspectmedical.com',
    apply_url: 'https://www.enerspectmedical.com',
    priority_score: 67,
    is_active: true,
    notes: 'D&B reporting confirmed. No PG. EIN required. Best for healthcare or medical businesses. Verify current apply URL on live site.',
  },
  {
    name: 'SupplyWorks (Home Depot Pro) Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Experian Business, Equifax Business',
    terms: 'Net 30 commercial account terms',
    pg_required: 'no',
    description: 'SupplyWorks (formerly Home Depot Pro) is a professional-grade janitorial, facility maintenance, and MRO supply company. Commercial accounts report to Experian Business and Equifax Business. No PG for commercial entities. Ideal for property managers, hospitality, and facilities businesses.',
    learn_more_url: 'https://www.supplyworks.com',
    apply_url: 'https://www.supplyworks.com',
    priority_score: 72,
    is_active: true,
    notes: 'Experian Business + Equifax Business dual-bureau confirmed. No PG for commercial entities. EIN required. Best for property management, hospitality, healthcare facilities, or janitorial businesses. Formerly known as Home Depot Pro.',
  },
  {
    name: 'CleanItSupply Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Janitorial and cleaning supply vendor offering net-30 accounts that report to D&B. No PG. Good entry-level PAYDEX tradeline for businesses in cleaning, facilities, or property management sectors.',
    learn_more_url: 'https://www.cleanitsupply.com',
    apply_url: 'https://www.cleanitsupply.com',
    priority_score: 69,
    is_active: true,
    notes: 'D&B reporting confirmed. No PG. EIN required. Best for cleaning services, janitorial companies, or property management businesses.',
  },
  {
    name: 'PC Nation Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'IT hardware and computer equipment vendor offering net-30 business accounts that report to D&B. No PG. Good for tech-oriented businesses needing computers, peripherals, or networking equipment while building D&B PAYDEX history.',
    learn_more_url: 'https://www.pcnation.com',
    apply_url: 'https://www.pcnation.com',
    priority_score: 68,
    is_active: true,
    notes: 'D&B reporting confirmed. No PG. EIN required. Best for businesses purchasing IT equipment, computers, or networking gear.',
  },
  {
    name: '4imprint Promotional Products Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Promotional products (branded merchandise, apparel, custom items) vendor with net-30 business accounts reporting to D&B. No PG. Wide range of customizable promotional items. Useful for marketing-oriented businesses building PAYDEX history.',
    learn_more_url: 'https://www.4imprint.com',
    apply_url: 'https://www.4imprint.com',
    priority_score: 70,
    is_active: true,
    notes: 'D&B reporting confirmed. No PG. EIN required. Broad product catalog — promotional items, branded merchandise, apparel, office accessories. Good for any business with marketing spend.',
  },
  {
    name: 'Amsterdam Printing Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Experian Business',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Promotional print products (business cards, banners, branded merchandise) vendor with net-30 accounts reporting to Experian Business. No PG. Useful for marketing-oriented businesses adding Experian Business tradelines.',
    learn_more_url: 'https://www.amsterdamprinting.com',
    apply_url: 'https://www.amsterdamprinting.com',
    priority_score: 67,
    is_active: true,
    notes: 'Experian Business reporting confirmed. No PG. EIN required. Best for businesses with marketing or promotional print spend.',
  },
  {
    name: 'Fastenal Commercial Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30 commercial account terms',
    pg_required: 'no',
    description: 'Fastenal industrial supply commercial net-30 account for fasteners, tools, safety equipment, and MRO supplies. Reports to D&B and Experian Business. No PG for established commercial entities. Dual-bureau reporting makes this a strong store credit tradeline.',
    learn_more_url: 'https://www.fastenal.com',
    apply_url: 'https://www.fastenal.com',
    priority_score: 74,
    is_active: true,
    notes: 'D&B and Experian Business dual-bureau reporting confirmed. No PG for commercial entities. EIN required. Best for construction, manufacturing, industrial, or facilities management businesses. Apply via Fastenal.com commercial credit application.',
  },
  {
    name: 'MSC Industrial Supply Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 commercial account terms',
    pg_required: 'no',
    description: 'MSC Industrial Direct offers metalworking, MRO, and industrial supply on net-30 commercial accounts. Reports to D&B. No PG for commercial entities. Strong PAYDEX tradeline for manufacturing, machining, or industrial businesses.',
    learn_more_url: 'https://www.mscdirect.com',
    apply_url: 'https://www.mscdirect.com',
    priority_score: 72,
    is_active: true,
    notes: 'D&B reporting confirmed. No PG for commercial entities. EIN required. Best for manufacturing, machining, CNC, or industrial businesses. Apply via commercial/corporate account section on mscdirect.com.',
  },
  {
    name: 'FairFigure Net 30 Tradeline',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Equifax Business, Creditsafe',
    terms: 'SaaS subscription-based net-30 tradeline, monthly fee applies',
    pg_required: 'no',
    description: 'FairFigure is a SaaS-based net-30 tradeline service specifically designed for business credit building. Subscription converts to a net-30 tradeline reported to Equifax Business and Creditsafe. No PG. Useful for adding Equifax Business and Creditsafe coverage when other vendors are limited.',
    learn_more_url: 'https://www.fairfigure.com',
    apply_url: 'https://www.fairfigure.com',
    priority_score: 66,
    is_active: true,
    notes: 'Reports to Equifax Business and Creditsafe — useful for rounding out multi-bureau coverage. No PG. Monthly subscription fee (verify current pricing on fairfigure.com). EIN required. Primarily a tradeline-building service, not a product/service vendor.',
  },

  // ── Fleet & Gas Stage ──
  {
    name: 'WEX Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 15 or Net 30, accepted at 95%+ gas stations',
    pg_required: 'yes',
    description: 'Fleet fuel card reporting to D&B and Experian Business. Available to businesses with any vehicle or equipment usage. PG generally required; EIN-only options available for very strong established fleets. Does not report to personal bureaus.',
    learn_more_url: 'https://www.wexinc.com/solutions/fleet-cards/',
    apply_url: 'https://www.wexinc.com/solutions/fleet-cards/',
    priority_score: 85,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed. PG required for most small businesses; EIN-only available for strong established fleets. 1–2 years in business preferred. Personal FICO ~640+ when PG applies. EIN and business bank account required.',
  },
  {
    name: 'Fuelman Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Net 15, nationwide acceptance, Basic/Pro/Enterprise plans',
    pg_required: 'varies',
    description: 'Fuelman (a FleetCor brand) fleet card with tri-bureau business reporting. Reports to D&B, Experian Business, and Equifax Business. EIN-only options available for established fleets with strong business credit. Available in Basic, Pro, and Enterprise plans.',
    learn_more_url: 'https://www.fuelman.com',
    apply_url: 'https://www.fuelman.com',
    priority_score: 80,
    is_active: true,
    notes: 'Tri-bureau reporting confirmed. PG varies — established fleets with 3+ years and strong credit may qualify EIN-only; newer businesses typically require PG. 1 year in business minimum. EIN and business bank account required. Verify current Apply URL on fuelman.com.',
  },
  {
    name: 'BP Business Solutions Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: null,
    terms: 'No longer available as a standalone product',
    pg_required: 'varies',
    description: 'DISCONTINUED — The BP Business Solutions fleet card brand has been superseded by the WEX/bp earnify fleet card program. Apply for the earnify fleet card via WEX or BP fleet card pages.',
    learn_more_url: 'https://www.wexinc.com/solutions/fleet-cards/',
    apply_url: 'https://www.wexinc.com/solutions/fleet-cards/',
    priority_score: 0,
    is_active: false,
    notes: 'DISCONTINUED — Legacy BP Business Solutions brand replaced by WEX/bp earnify fleet card. Direct clients to WEX fleet cards section. Reporting via WEX to D&B and Experian Business.',
  },
  {
    name: 'CITGO Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30; accepted at CITGO locations nationwide',
    pg_required: 'yes',
    description: 'CITGO Fleet Card powered by WEX. Reports to D&B and Experian Business following WEX\'s dual-bureau reporting model. Multiple card options (CITGO Fleet, Fleet Select, Fleet Universal) with up to 5¢/gal rebates at CITGO locations.',
    learn_more_url: 'https://www.citgofleetcard.com',
    apply_url: 'https://www.citgofleetcard.com',
    priority_score: 72,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed via WEX platform. PG required for most small businesses; EIN-only for strong established fleets. 1–2 years in business preferred. EIN and business bank account required. Powered by WEX.',
  },
  {
    name: 'Shell Fleet Solutions Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Net 30; Shell Card Business or Shell Card Business Flex (~95% station acceptance)',
    pg_required: 'varies',
    description: 'Shell Fleet Solutions (WEX Bank issued) with dual or tri-bureau reporting. Shell Card Business Flex reports to all three major business bureaus and has near-universal acceptance. Shell Card Business follows D&B + Experian pattern. EIN-only available for $1M+ annual revenue businesses.',
    learn_more_url: 'https://www.businessfleetsolutions.com',
    apply_url: 'https://www.businessfleetsolutions.com',
    priority_score: 76,
    is_active: true,
    notes: 'Shell Card Business Flex is tri-bureau (D&B + Experian Business + Equifax Business). Standard Shell Card Business follows D&B + Experian pattern. PG varies — EIN-only for $1M+ annual revenue; smaller businesses expect PG. 1+ year in business. EIN required.',
  },
  {
    name: 'Sunoco Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30; Sunoco Fleet Universal Card or Sunoco Business Fleet Card',
    pg_required: 'varies',
    description: 'Sunoco fleet cards powered by WEX. Reports to D&B and Experian Business. Two options: Sunoco Fleet Universal Card (95% station acceptance) or Sunoco Business Fleet Card (Sunoco stations, up to 15¢/gal promo rebates for first 6 months).',
    learn_more_url: 'https://www.sunoco.com/sunoco-fleet-universal-card',
    apply_url: 'https://www.sunoco.com/sunoco-fleet-universal-card',
    priority_score: 70,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed via WEX platform. PG varies — most small operators expect PG; strong established fleets may qualify EIN-only. EIN and business bank account required. Two product options: Universal (broad acceptance) or Business Fleet Card (Sunoco stations, higher rebates).',
  },
  {
    name: 'Speedway Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30; accepted at 7-Eleven, Speedway, and Stripes locations + ~95% nationwide via WEX',
    pg_required: 'varies',
    description: 'Speedway fleet card now integrated into 7-Eleven\'s WEX-powered fleet platform. Program is active post-acquisition. Reports to D&B and Experian Business via WEX. Earns rebates at 7-Eleven, Speedway, and Stripes locations.',
    learn_more_url: 'https://www.speedwayfleetcards.com',
    apply_url: 'https://www.speedwayfleetcards.com',
    priority_score: 65,
    is_active: true,
    notes: 'Program confirmed active — integrated into 7-Eleven/WEX fleet platform post-acquisition. D&B and Experian Business reporting via WEX confirmed. PG varies — most small fleets expect PG. EIN and business bank account required.',
  },

  // ── Fleet & Gas Stage — New Additions ──
  {
    name: 'AtoB Fuel Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Accepted anywhere Visa is accepted; flexible billing terms',
    pg_required: 'no',
    description: 'AtoB is a flexible fleet fuel card accepted anywhere Visa is accepted — not limited to a single fuel network. Tri-bureau business reporting to D&B, Experian Business, and Equifax Business. No-PG options available for businesses with established history.',
    learn_more_url: 'https://www.atob.com',
    apply_url: 'https://www.atob.com',
    priority_score: 88,
    is_active: true,
    notes: 'Tri-bureau reporting confirmed. Significant advantage over WEX-network-only fleet cards — accepted wherever Visa is accepted. No-PG for established businesses. EIN required. Business bank account required.',
  },
  {
    name: 'Valero Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30; accepted at Valero, Diamond Shamrock, and Shamrock stations',
    pg_required: 'varies',
    description: 'Valero fleet card for businesses with fuel purchasing needs at Valero, Diamond Shamrock, and Shamrock stations. Reports to D&B and Experian Business. PG may be required for new or thin-file businesses but can be removed over time.',
    learn_more_url: 'https://www.valero.com',
    apply_url: 'https://www.valero.com',
    priority_score: 72,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed. PG varies — can be removed over time as business credit strengthens. EIN required. Best for businesses operating in Valero/Diamond Shamrock/Shamrock fuel coverage areas.',
  },

  // ── Fleet & Gas Stage — Trucking Additions ──
  {
    name: 'Coast Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Experian Business, Equifax Business',
    terms: 'Accepted anywhere Visa is accepted; flexible billing',
    pg_required: 'no',
    description: 'Coast is a flexible no-PG fleet card accepted wherever Visa is accepted — not network-restricted. Reports to Experian Business and Equifax Business. Dual-bureau coverage with broad acceptance makes it one of the strongest no-PG fleet options for businesses of any size.',
    learn_more_url: 'https://www.coastpay.com',
    apply_url: 'https://www.coastpay.com',
    priority_score: 86,
    is_active: true,
    notes: 'Experian Business + Equifax Business dual-bureau confirmed. No PG — underwriting based on business financials. Visa-network accepted. EIN required. Business bank account required. Strong alternative to AtoB for businesses needing Visa acceptance without PG.',
  },
  {
    name: 'OTR Solutions Fuel Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet',
    terms: 'Weekly settlement, fuel advance options, trucking-specific',
    pg_required: 'varies',
    description: 'OTR Solutions fuel card and freight factoring product for trucking and long-haul fleets. Reports primarily to D&B. Includes fuel advance features tied to freight invoices. Designed specifically for owner-operators and small trucking fleets.',
    learn_more_url: 'https://www.otrsolutions.com',
    apply_url: 'https://www.otrsolutions.com',
    priority_score: 72,
    is_active: true,
    notes: 'D&B reporting confirmed. PG varies — established trucking operators may qualify without PG. Primarily for trucking/freight industry clients. EIN and MC number (motor carrier) may be required. Fuel advance tied to freight invoice factoring.',
  },
  {
    name: 'EFS (Electronic Funds Source) Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net terms (weekly/monthly), accepted at 47,000+ locations, trucking-focused',
    pg_required: 'no',
    description: 'EFS (a WEX company) fleet card designed for trucking and transportation fleets. Reports to D&B. No-PG options for established fleets. Accepted at 47,000+ fuel locations. Includes fuel management, driver controls, and IFTA reporting tools.',
    learn_more_url: 'https://www.wexinc.com/solutions/fleet-cards/transportation/',
    apply_url: 'https://www.wexinc.com/solutions/fleet-cards/transportation/',
    priority_score: 74,
    is_active: true,
    notes: 'D&B reporting confirmed. No PG available for established fleets (1+ year, strong business credit). Part of WEX company family. MC/DOT numbers may be required for trucking-specific accounts. Best for transportation and trucking businesses.',
  },
  {
    name: 'ExxonMobil FleetPro Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30; accepted at Exxon and Mobil stations nationwide',
    pg_required: 'varies',
    description: 'ExxonMobil FleetPro fleet card accepted at all Exxon and Mobil stations. Reports to D&B and Experian Business. PG may be waived for established businesses with strong credit. Fuel rebates and fleet management controls included.',
    learn_more_url: 'https://fleetpro.exxonmobil.com',
    apply_url: 'https://fleetpro.exxonmobil.com',
    priority_score: 73,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed. PG varies — strong established businesses may qualify without. EIN and business bank account required. Accepted at Exxon and Mobil stations. Apply at fleetpro.exxonmobil.com.',
  },

  // ── Equipment Financing Stage ──
  {
    name: 'Beacon Funding Equipment Financing',
    program: 'program_b',
    stage: 'Equipment Financing',
    category: 'funding',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Equipment leases and loans; terms vary by equipment type and amount',
    pg_required: 'varies',
    description: 'Beacon Funding specializes in commercial vehicle and equipment leasing for businesses. Reports to major business bureaus. PG varies by deal size and business credit strength. EIN-only options available for strong credit profiles. Excellent for building equipment tradelines.',
    learn_more_url: 'https://www.beaconfunding.com',
    apply_url: 'https://www.beaconfunding.com',
    priority_score: 78,
    is_active: true,
    notes: 'Major business bureau reporting confirmed. PG varies — strong business credit may qualify EIN-only. Best for transportation, construction, or any business needing commercial vehicles or equipment. EIN required. Multiple equipment categories.',
  },
  {
    name: 'Commercial Credit Group (CCG) Equipment Financing',
    program: 'program_b',
    stage: 'Equipment Financing',
    category: 'funding',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Equipment loans and leases; 2–7 year terms typical',
    pg_required: 'varies',
    description: 'Commercial Credit Group focuses on heavy equipment financing for construction, transportation, and waste management industries. Reports to major business bureaus. PG varies — experienced operators in key industries can sometimes qualify without PG.',
    learn_more_url: 'https://www.comcredgroup.com',
    apply_url: 'https://www.comcredgroup.com',
    priority_score: 76,
    is_active: true,
    notes: 'Major business bureau reporting confirmed. PG varies. Targets construction, transportation, agriculture, and waste management sectors. EIN required. Specializes in industries with hard-to-finance heavy equipment.',
  },
  {
    name: 'United Rentals Business Account',
    program: 'program_b',
    stage: 'Equipment Financing',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30 commercial account for equipment rentals',
    pg_required: 'no',
    description: 'United Rentals is the largest equipment rental company in North America. Commercial net-30 accounts report to D&B and Experian Business. No PG for established businesses. Excellent tradeline for construction, infrastructure, and industrial businesses.',
    learn_more_url: 'https://www.unitedrentals.com',
    apply_url: 'https://www.unitedrentals.com/en/accounts/credit-application',
    priority_score: 80,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed. No PG for established commercial entities. EIN required. Best for construction, property development, or industrial businesses with regular equipment rental needs. Apply via credit application on unitedrentals.com.',
  },
  {
    name: 'OnDeck Equipment Financing',
    program: 'program_b',
    stage: 'Equipment Financing',
    category: 'funding',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Equipment loans up to $250K; 12–60 month terms',
    pg_required: 'yes',
    description: 'OnDeck offers small business equipment loans with tri-bureau business reporting. PG required. Minimum 625+ personal FICO, 1+ year in business, $100K+ annual revenue. Fast funding (1–3 days). Good option for established businesses needing equipment financing tradelines.',
    learn_more_url: 'https://www.ondeck.com',
    apply_url: 'https://www.ondeck.com',
    priority_score: 74,
    is_active: true,
    notes: 'Tri-bureau business reporting confirmed. PG required. Min 625+ FICO, 1+ year in business, $100K+ annual revenue. Fast approvals — 1–3 day funding typical. Equipment must be business-use. EIN and SSN of guarantor required.',
  },
  {
    name: 'National Funding Equipment Financing',
    program: 'program_b',
    stage: 'Equipment Financing',
    category: 'funding',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Equipment loans and leases up to $500K; 2–5 year terms',
    pg_required: 'yes',
    description: 'National Funding offers equipment financing and working capital loans with major bureau reporting. Flexible qualifications — as low as 600 FICO, 6+ months in business. Broad equipment categories including restaurant, medical, construction, and tech equipment.',
    learn_more_url: 'https://www.nationalfunding.com',
    apply_url: 'https://www.nationalfunding.com',
    priority_score: 72,
    is_active: true,
    notes: 'Major business bureau reporting confirmed. PG required. Flexible — as low as 600 FICO and 6 months in business. Up to $500K financing. Covers restaurant, medical, construction, vehicles, and more. EIN required.',
  },
  {
    name: 'Direct Capital (CIT Bank) Equipment Financing',
    program: 'program_b',
    stage: 'Equipment Financing',
    category: 'funding',
    reports_to: 'Equifax Business, Experian Business',
    terms: 'Equipment leases and loans up to $500K; flexible terms',
    pg_required: 'yes',
    description: 'Direct Capital (a CIT Bank company) specializes in equipment financing and small business leasing. Reports to Equifax Business and Experian Business. PG required for most small businesses. Broad equipment categories. Good mid-market equipment tradeline.',
    learn_more_url: 'https://www.directcapital.com',
    apply_url: 'https://www.directcapital.com',
    priority_score: 70,
    is_active: true,
    notes: 'Equifax Business and Experian Business reporting confirmed. PG required. Part of CIT Bank / First Citizens Bank family (post-acquisition). Up to $500K financing available. EIN required.',
  },

  // ── Cash & Revolving Stage ──
  {
    name: 'BILL Spend & Expense (formerly Divvy)',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'No annual fee, corporate charge card, full monthly payment required',
    pg_required: 'no',
    description: 'BILL Spend & Expense (formerly Divvy) is a corporate charge card and expense management platform. No personal guarantee. Reports to business bureaus via SBFE — data flows to D&B, Experian Business, and Equifax Business. Includes budgets, virtual cards, and integrated expense reporting.',
    learn_more_url: 'https://www.bill.com/product/spend-and-expense',
    apply_url: 'https://www.bill.com/product/spend-and-expense',
    priority_score: 95,
    is_active: true,
    notes: 'Formerly Divvy — now BILL Spend & Expense. Bureau reporting via SBFE (multi-bureau distribution). No PG. Soft pull only on personal credit. EIN required. Must connect business bank accounts. Corporate charge card — balance paid monthly.',
  },
  {
    name: 'Ramp Business Credit Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'No fees, 1.5% cash back, charge card (full monthly payment)',
    pg_required: 'no',
    description: 'Corporate card with no personal guarantee and no personal credit check. Underwriting based on business finances and bank balances. Reports to D&B and Experian Business. 1.5% cash back. Typical minimum cash balance requirement $50K–$75K+ (verify directly — not publicly disclosed).',
    learn_more_url: 'https://ramp.com',
    apply_url: 'https://ramp.com',
    priority_score: 88,
    is_active: true,
    notes: 'No PG confirmed. Reports to D&B and Experian Business (not Equifax Business). Must connect business bank accounts. Minimum cash balance not publicly disclosed — previously cited at $25K but current guidance suggests $50K–$75K+; verify directly with Ramp. EIN required. Incorporated businesses only (no sole props).',
  },
  {
    name: 'Brex Business Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'No annual fee, high limits, no personal guarantee',
    pg_required: 'no',
    description: 'Corporate card for funded startups and scaling businesses. No personal guarantee. Reports to D&B and Experian Business via SBFE. Primarily serves funded startups ($50K+ cash), mid-market companies ($400K+/month revenue), or commercial businesses ($1M+ annual revenue).',
    learn_more_url: 'https://www.brex.com',
    apply_url: 'https://www.brex.com',
    priority_score: 82,
    is_active: true,
    notes: 'No PG confirmed. D&B and Experian Business reporting confirmed (via SBFE). Requirements: funded startups with $50K+ cash balance; or $400K+/month revenue (mid-market); or $1M+ annual revenue (commercial). Not accessible for typical small LLCs with modest revenue. Incorporated entities only.',
  },
  {
    name: 'American Express Corporate Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Corporate charge card; monthly billing; no preset spending limit',
    pg_required: 'no',
    description: 'American Express Corporate Card for established corporations. No PG for standard corporate structure. Liability is on the company. Typically requires ~$5M+ annual revenue, 10+ employees, and 2+ years in business. Reports to D&B and Experian Business via SBFE.',
    learn_more_url: 'https://www.americanexpress.com/en-us/business/corporate-cards/',
    apply_url: 'https://www.americanexpress.com/en-us/business/corporate-cards/',
    priority_score: 70,
    is_active: true,
    notes: 'NOT appropriate for typical small businesses or new LLCs. Requires substantial corporate infrastructure (~$5M+ revenue, 10+ employees). No PG for standard corporate structure. D-U-N-S effectively required. Must be a corporation or equivalent entity.',
  },
  {
    name: 'Dell Business Credit',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30 or financing terms available',
    pg_required: 'yes',
    description: 'Dell Business Credit (WebBank-issued) offers net-30 purchasing and financing terms for computers, servers, and business technology. Reports to D&B and Experian Business. PG and personal credit check required for most small businesses.',
    learn_more_url: 'https://www.dell.com/en-us/lp/dell-business-credit',
    apply_url: 'https://www.dell.com/en-us/lp/dell-business-credit',
    priority_score: 78,
    is_active: true,
    notes: 'D&B and Experian Business reporting widely cited but not officially confirmed by issuer — verify via live tradeline. PG required for most small businesses (WebBank underwriting). Mid-600s+ personal FICO typically needed. EIN + SSN of guarantor required.',
  },
  {
    name: 'Lenovo Business Financing',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'vendor',
    reports_to: null,
    terms: 'Net 30 or financing terms; 0% intro financing on select products',
    pg_required: 'yes',
    description: 'Lenovo Business Financing provides net-30 terms and financing options on laptops, desktops, and servers. PG required for most small businesses. Bureau reporting is lender-dependent and unconfirmed — verify before recommending as a tradeline.',
    learn_more_url: 'https://www.lenovo.com/us/en/financing/',
    apply_url: 'https://www.lenovo.com/us/en/financing/',
    priority_score: 65,
    is_active: true,
    notes: 'PG required (corrected from previous no-PG claim). Bureau reporting UNCONFIRMED — lender-dependent (Lenovo partners with third-party lenders). Previous tri-bureau claim not supported by current evidence. Mid-600s+ personal FICO typically needed. EIN required.',
  },
  {
    name: 'Costco Business Credit Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: null,
    terms: 'No longer active as a business tradeline',
    pg_required: 'yes',
    description: 'REMOVED — The Costco Anywhere Visa Business Card (Citi-issued) reports to personal credit bureaus only (Equifax, Experian, TransUnion personal). It does not build business credit. An active Costco membership is required.',
    learn_more_url: 'https://www.costco.com/business-credit-card.html',
    apply_url: null,
    priority_score: 0,
    is_active: false,
    notes: 'REMOVED — Confirmed reports to personal bureaus only. Does not create a business tradeline. Removed per policy: all portal accounts must report to business credit bureaus.',
  },

  // ── Cash & Revolving Stage — New Additions ──
  {
    name: 'Stripe Corporate Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Experian Business',
    terms: 'Charge card with dynamic limits tied to Stripe processing volume',
    pg_required: 'no',
    description: 'Stripe Corporate Card for established Stripe merchants. No personal guarantee. Dynamic spending limits scale with Stripe processing volume. Requires active Stripe payments account with ~$4M+ annual processing volume. Bureau reporting inconsistent — some users report Experian Business.',
    learn_more_url: 'https://support.stripe.com/topics/corporate-card',
    apply_url: 'https://support.stripe.com/topics/corporate-card',
    priority_score: 58,
    is_active: true,
    notes: 'Bureau reporting UNCONFIRMED — some community reports of Experian Business but not officially guaranteed. No PG. Must be an active Stripe merchant in good standing with KYC up to date. Primarily accessible via Stripe dashboard for eligible merchants. Not a primary credit-building vehicle until reporting is more transparent.',
  },
  {
    name: 'Mercury IO Business Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Experian Business, Equifax Business',
    terms: 'No annual fee, ~1.5% cash back, charge card (balance-backed)',
    pg_required: 'no',
    description: 'Mercury IO is a no-PG corporate card backed by your Mercury bank balance. Reports to Experian Business and Equifax Business. Spending limits derived from deposit balance. Metal IO card available for accounts with $50K+ in deposits. Must hold a Mercury business bank account.',
    learn_more_url: 'https://mercury.com',
    apply_url: 'https://mercury.com',
    priority_score: 72,
    is_active: true,
    notes: 'Experian Business and Equifax Business reporting confirmed by Mercury. No PG. No personal credit check — identity verification required. Must have Mercury business bank account. Card limits = deposit balance. EIN required. Best for startups and tech businesses banking with Mercury.',
  },
  {
    name: 'Rho Corporate Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Experian Business',
    terms: 'Corporate charge card, flexible terms adjustable up to 4x/year',
    pg_required: 'no',
    description: 'Rho corporate card for venture-backed and fast-growing businesses. No personal guarantee. Reports to Experian Business. Spending limits scale with business growth. Requires Rho banking account. Corporations, LLCs, and LPs eligible — no sole props.',
    learn_more_url: 'https://www.rho.co',
    apply_url: 'https://www.rho.co',
    priority_score: 68,
    is_active: true,
    notes: 'Experian Business reporting confirmed by Rho. No PG. No collateral. Must adopt Rho banking platform. Targets venture-backed and fast-growing businesses — not ideal for typical small LLCs with modest revenue. EIN + formation documents required.',
  },
  {
    name: 'Corpay One Mastercard',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet',
    terms: 'Business credit card integrated with automated accounts payable platform',
    pg_required: 'no',
    description: 'Corpay One (formerly Comdata) Mastercard integrates business credit with an automated bill-pay platform. Reports to D&B. No-PG options for established businesses. Unique value: combines business spending with automated AP workflow.',
    learn_more_url: 'https://www.corpayone.com',
    apply_url: 'https://www.corpayone.com',
    priority_score: 74,
    is_active: true,
    notes: 'D&B reporting confirmed. No-PG options for established businesses. EIN required. Business bank account required. Best for businesses looking to combine credit building with automated accounts payable.',
  },
  {
    name: 'Capital on Tap Business Credit Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Revolving credit, high limits, no annual fee options',
    pg_required: 'yes',
    description: 'Capital on Tap is specifically designed for small businesses with high credit limits and no annual fee options. Reports to D&B and Experian Business. PG required. Good mid-tier Cash & Revolving option for clients with established personal and business credit.',
    learn_more_url: 'https://www.capitalontap.com',
    apply_url: 'https://www.capitalontap.com/en/',
    priority_score: 78,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed. PG required. Designed specifically for small businesses — more accessible than corporate-only cards. EIN required.',
  },
  {
    name: 'First National Bank of Omaha (FNBO) Business Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Revolving credit, multiple card products (rewards, points, cash back)',
    pg_required: 'yes',
    description: 'FNBO Business Editions is a suite of business credit cards (revolving and points-based) that report to D&B and Experian Business. PG required. Multiple card options to match different spending profiles.',
    learn_more_url: 'https://www.fnbo.com/business/credit-cards/',
    apply_url: 'https://www.fnbo.com/business/credit-cards/',
    priority_score: 72,
    is_active: true,
    notes: 'D&B and Experian Business reporting confirmed. PG required. Multiple card products available. EIN required.',
  },
  {
    name: 'Navy Federal Business Solutions Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Experian Business, Equifax Business',
    terms: 'Revolving business credit card',
    pg_required: 'yes',
    description: 'Navy Federal Credit Union business credit card reporting to Experian Business and Equifax Business. PG required. Dual-bureau business reporting with competitive rates. Membership restricted to military, DoD employees, and their families.',
    learn_more_url: 'https://www.navyfederal.org/loans-cards/credit-cards/business.html',
    apply_url: 'https://www.navyfederal.org/loans-cards/credit-cards/business.html',
    priority_score: 70,
    is_active: true,
    notes: 'Experian Business + Equifax Business dual-bureau confirmed. PG required. MEMBERSHIP REQUIRED — restricted to military members, DoD civilians, contractors, and immediate family members. Only recommend to eligible clients.',
  },
  {
    name: 'DCU Business Visa Credit Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Experian Business',
    terms: 'Revolving credit, low rates',
    pg_required: 'yes',
    description: 'Digital Federal Credit Union (DCU) business Visa reporting to Experian Business. PG required. Known for low rates and simple revolving credit for small businesses. Credit union membership required.',
    learn_more_url: 'https://www.dcu.org/borrow/credit-cards/business-credit-cards.html',
    apply_url: 'https://www.dcu.org/borrow/credit-cards/business-credit-cards.html',
    priority_score: 64,
    is_active: true,
    notes: 'Experian Business reporting confirmed. PG required. MEMBERSHIP REQUIRED — DCU credit union membership required to apply. Only recommend to eligible clients.',
  },
  {
    name: 'America First Credit Union Business Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Experian Business',
    terms: 'Revolving business credit card, rewards options available',
    pg_required: 'yes',
    description: 'America First Credit Union business credit card reporting to Experian Business. PG required. Offers rewards-based business Visa options. Credit union membership required — primarily serves Utah, Nevada, and surrounding states.',
    learn_more_url: 'https://www.americafirst.com/business/credit-cards.html',
    apply_url: 'https://www.americafirst.com/business/credit-cards.html',
    priority_score: 62,
    is_active: true,
    notes: 'Experian Business reporting confirmed. PG required. MEMBERSHIP AND REGIONAL RESTRICTION — primarily serves Utah, Nevada, Idaho, Oregon, and Arizona. Only recommend to clients in eligible service areas.',
  },
  {
    name: 'Truist Business Cash Rewards Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Equifax Business',
    terms: 'Revolving business credit card, cash rewards',
    pg_required: 'yes',
    description: 'Truist Business Cash Rewards card (formed by SunTrust/BB&T merger) reports to D&B and Equifax Business. PG required. Useful D&B + Equifax dual-bureau option. Primary presence in Southeast and Mid-Atlantic states.',
    learn_more_url: 'https://www.truist.com/small-business/credit-cards',
    apply_url: 'https://www.truist.com/small-business/credit-cards',
    priority_score: 68,
    is_active: true,
    notes: 'D&B and Equifax Business reporting confirmed. PG required. REGIONAL — primary presence in Southeast and Mid-Atlantic (GA, FL, NC, SC, VA, MD, etc.). Only recommend to clients in Truist service areas. EIN required.',
  },
  {
    name: 'FairFigure Capital Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Revolving charge card, cash-flow underwriting, no personal FICO minimum',
    pg_required: 'no',
    description: 'FairFigure Capital Card uses cash-flow-based underwriting instead of personal credit scores. Tri-bureau business reporting to D&B, Experian Business, and Equifax Business. No PG. Access based on business bank account performance, not personal FICO. Strong option for business owners with lower personal credit.',
    learn_more_url: 'https://www.fairfigure.com',
    apply_url: 'https://www.fairfigure.com',
    priority_score: 80,
    is_active: true,
    notes: 'Tri-bureau reporting confirmed. No PG. Cash-flow underwriting — no personal FICO requirement. Must connect business bank account. EIN required. Particularly valuable for clients with strong business revenue but lower personal credit scores.',
  },
  {
    name: 'FNBO Business Edition Secured Mastercard',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: 'Secured card — 110% deposit of credit limit; up to $100,000 credit limit',
    pg_required: 'yes',
    description: 'FNBO Business Edition Secured Mastercard is a secured business card with unusually high limits — up to $100K with a 110% security deposit. Tri-bureau business bureau reporting. PG required. Ideal for businesses with strong cash reserves but limited business credit history.',
    learn_more_url: 'https://www.fnbo.com/business/credit-cards/',
    apply_url: 'https://www.fnbo.com/business/credit-cards/',
    priority_score: 75,
    is_active: true,
    notes: 'Tri-bureau business reporting confirmed. PG required. SECURED — requires 110% of credit limit as deposit (e.g., $11K deposit for $10K limit). Up to $100K available. Excellent for businesses with cash reserves wanting to accelerate business credit with high-limit tri-bureau tradeline. EIN required.',
  },
]

// ─── Program C — Capital Monitoring Membership ────────────────────────────────
const PROGRAM_C: DefaultOpportunity[] = [
  {
    name: 'Nav Business Credit Monitoring (Premium)',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'monitoring',
    reports_to: 'Dun & Bradstreet, Experian Business, Equifax Business',
    terms: '~$40–$75/month or $199+/year (verify current tier pricing at nav.com/pricing)',
    pg_required: 'n/a',
    description: 'Full monitoring of business and personal credit across all major bureaus. Includes D&B, Experian Intelliscore, and Equifax Business score visibility. Nav Prime/Business Boost tier adds a reporting tradeline to business bureaus. Used in monthly capital readiness snapshots.',
    learn_more_url: 'https://www.nav.com',
    apply_url: 'https://www.nav.com/pricing/',
    priority_score: 95,
    is_active: true,
    notes: 'Pricing updated — legacy $49.99/month figure outdated; current plans run ~$40–$75/month or $199+/year. Nav Prime/Boost tier creates a reporting tradeline to business bureaus. Confirm which scores (PAYDEX, Intelliscore) are visible on current plan inside Nav dashboard.',
  },
  {
    name: 'CreditSafe Business Monitor',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'monitoring',
    reports_to: null,
    terms: 'Self-serve MYC (Manage Your Company) plan available; enterprise pricing custom',
    pg_required: 'n/a',
    description: 'CreditSafe business credit monitoring platform. Provides real-time alerts, risk scores, and competitor benchmarking. The MYC self-serve tool allows businesses to claim and monitor their own CreditSafe profile. Monitoring only — does not submit tradelines to D&B, Experian, or Equifax.',
    learn_more_url: 'https://www.creditsafe.com/us/',
    apply_url: 'https://www.creditsafe.com/us/en/solutions/myc.html',
    priority_score: 80,
    is_active: true,
    notes: 'MONITORING ONLY — CreditSafe does not report tradelines to D&B, Experian Business, or Equifax Business. It compiles its own proprietary data. MYC self-serve product available for small businesses at creditsafe.com/us/en/solutions/myc.html. Enterprise pricing is quote-based.',
  },
  {
    name: 'Fundbox Line of Credit',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'funding',
    reports_to: 'Dun & Bradstreet',
    terms: 'Up to $150K revolving LOC, weekly or 12/24-week repayment terms',
    pg_required: 'yes',
    description: 'Revolving business line of credit reporting to D&B. Minimum 600 personal FICO, 6+ months in business, and $30K+ annual revenue ($100K+ practical threshold). Business checking account required — Fundbox analyzes 3+ months of bank transactions. Funded in 1–3 days.',
    learn_more_url: 'https://fundbox.com',
    apply_url: 'https://fundbox.com',
    priority_score: 82,
    is_active: true,
    notes: 'D&B reporting confirmed. PG required. Qualifications: 600+ personal FICO, 6+ months in business, $30K minimum annual revenue ($100K practical threshold), business checking required (3+ months transactions analyzed). Max LOC $150K. No prepayment penalties.',
  },
  {
    name: 'Bluevine Business Line of Credit',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'funding',
    reports_to: 'Experian Business',
    terms: 'Up to $250K revolving LOC, 6 or 12 month terms',
    pg_required: 'yes',
    description: 'Flexible revolving line of credit reporting to Experian Business. Requires 625+ personal FICO, 12+ months in business, and $10K+/month ($120K/year) minimum revenue. Business checking account required. Good capital readiness benchmark target.',
    learn_more_url: 'https://www.bluevine.com',
    apply_url: 'https://www.bluevine.com',
    priority_score: 85,
    is_active: true,
    notes: 'Experian Business reporting confirmed. D&B and Equifax Business not confirmed. PG required. Qualifications: 625+ personal FICO, 12 months in business minimum, $10K/month ($120K/year) revenue — revenue requirement corrected from previous $40K/month figure. Max LOC $250K. No prepayment penalties.',
  },
  {
    name: 'Kabbage (American Express Business Blueprint)',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'funding',
    reports_to: 'Equifax Business',
    terms: 'Up to $250K LOC, 6, 12, or 18 month terms',
    pg_required: 'yes',
    description: 'Revolving credit line now under American Express (formerly Kabbage). Known for flexible qualification criteria. Good for businesses with consistent revenue but mixed credit. Reports to Equifax Business.',
    learn_more_url: 'https://www.americanexpress.com/en-us/business/blueprint/',
    apply_url: 'https://www.americanexpress.com/en-us/business/blueprint/',
    priority_score: 78,
    is_active: true,
    notes: 'VERIFY — Kabbage/Amex Blueprint was not fully verified in this research pass. Confirm current product availability, URL, and qualification requirements directly. Equifax Business reporting widely cited but confirm with live data.',
  },
]

export const DEFAULT_OPPORTUNITIES: DefaultOpportunity[] = [
  ...PROGRAM_A,
  ...PROGRAM_B,
  ...PROGRAM_C,
]
