export interface DefaultOpportunity {
  name: string
  program: string
  stage: string
  category: string
  reports_to: string | null
  terms: string | null
  pg_required: string
  description: string | null
  learn_more_url: string | null
  apply_url: string | null
  priority_score: number
  is_active: boolean
  notes: string | null
}

// ─── Program A — 0% APR Card Strategy ────────────────────────────────────────
const PROGRAM_A: DefaultOpportunity[] = [
  // ── Credit Readiness Stage ──
  {
    name: 'Experian Boost',
    program: 'program_a',
    stage: 'Credit Readiness',
    category: 'monitoring',
    reports_to: 'Experian',
    terms: 'Free',
    pg_required: 'n/a',
    description: 'Add utility, phone, and streaming payments to your Experian credit file. Can raise your FICO score by up to 10-20 points instantly.',
    learn_more_url: 'https://www.experian.com/consumer-products/score-boost.html',
    apply_url: 'https://www.experian.com/consumer-products/score-boost.html',
    priority_score: 95,
    is_active: true,
    notes: 'Start here — free and immediate impact',
  },
  {
    name: 'Self Credit Builder Account',
    program: 'program_a',
    stage: 'Credit Readiness',
    category: 'funding',
    reports_to: 'Equifax, Experian, TransUnion',
    terms: '$25–$150/month, 12–24 month term',
    pg_required: 'no',
    description: 'A credit-builder loan that reports monthly payments to all 3 bureaus. Ideal for thin files. Funds are held in a savings account and released when paid off.',
    learn_more_url: 'https://www.self.inc',
    apply_url: 'https://www.self.inc',
    priority_score: 80,
    is_active: true,
    notes: 'Good for adding positive payment history before card applications',
  },
  {
    name: 'Secured Discover it Card',
    program: 'program_a',
    stage: 'Credit Readiness',
    category: 'funding',
    reports_to: 'Equifax, Experian, TransUnion',
    terms: '$200 minimum deposit, no annual fee',
    pg_required: 'yes',
    description: 'A secured card that graduates to unsecured after 7 months of on-time payments. Reports to all 3 bureaus. Good stepping stone for those under 640 FICO.',
    learn_more_url: 'https://www.discover.com/credit-cards/secured/',
    apply_url: 'https://www.discover.com/credit-cards/secured/',
    priority_score: 75,
    is_active: true,
    notes: 'Use if FICO is below 640 to build before applying for 0% APR cards',
  },

  // ── Application Strategy Stage ──
  {
    name: 'Chase Ink Business Unlimited',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Equifax, Experian (business)',
    terms: '0% intro APR 12 months, unlimited 1.5% cash back, no annual fee',
    pg_required: 'yes',
    description: 'One of the top 0% intro APR business cards. No annual fee and unlimited 1.5% cash back. Ideal first business card in the Program A stack.',
    learn_more_url: 'https://creditcards.chase.com/business-credit-cards/ink/unlimited',
    apply_url: 'https://creditcards.chase.com/business-credit-cards/ink/unlimited',
    priority_score: 98,
    is_active: true,
    notes: 'Apply first — typically highest approval odds and best terms',
  },
  {
    name: 'Chase Ink Business Cash',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Equifax, Experian (business)',
    terms: '0% intro APR 12 months, 5% on office/internet, no annual fee',
    pg_required: 'yes',
    description: 'Pairs with Chase Ink Unlimited for category-specific spending. 5% back at office stores and on internet/cable/phone. No annual fee.',
    learn_more_url: 'https://creditcards.chase.com/business-credit-cards/ink/cash',
    apply_url: 'https://creditcards.chase.com/business-credit-cards/ink/cash',
    priority_score: 95,
    is_active: true,
    notes: 'Apply same day or within 2 days of Ink Unlimited',
  },
  {
    name: 'US Bank Business Triple Cash Rewards',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Equifax, Experian (business)',
    terms: '0% intro APR 15 billing cycles, 3% cash back on eligible purchases, no annual fee',
    pg_required: 'yes',
    description: 'Longest 0% APR period in the stack at 15 billing cycles. 3% back on eligible business categories. No annual fee.',
    learn_more_url: 'https://www.usbank.com/business/credit-cards/triple-cash-rewards-business-credit-card.html',
    apply_url: 'https://www.usbank.com/business/credit-cards/triple-cash-rewards-business-credit-card.html',
    priority_score: 90,
    is_active: true,
    notes: 'Apply after Chase cards — requires established business banking relationship ideal',
  },
  {
    name: 'Bank of America Business Advantage Unlimited Cash',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Equifax, Experian (business)',
    terms: '0% intro APR 9 billing cycles, unlimited 1.5% cash back, no annual fee',
    pg_required: 'yes',
    description: 'Good addition to the 0% APR stack. Preferred Rewards members get higher cash back rates. No annual fee.',
    learn_more_url: 'https://www.bankofamerica.com/smallbusiness/credit-cards/unlimited-cash-rewards/',
    apply_url: 'https://www.bankofamerica.com/smallbusiness/credit-cards/unlimited-cash-rewards/',
    priority_score: 82,
    is_active: true,
    notes: 'Bonus if client has existing BofA accounts',
  },
  {
    name: 'Capital One Spark Cash Plus',
    program: 'program_a',
    stage: 'Application Strategy',
    category: 'funding',
    reports_to: 'Equifax, Experian, TransUnion (business)',
    terms: 'No preset spending limit, 2% unlimited cash back, $150 annual fee',
    pg_required: 'yes',
    description: 'Charge card with no preset limit — useful for high-spend months without utilization impact. 2% unlimited cash back.',
    learn_more_url: 'https://www.capitalone.com/small-business/credit-cards/spark-cash-plus/',
    apply_url: 'https://www.capitalone.com/small-business/credit-cards/spark-cash-plus/',
    priority_score: 78,
    is_active: true,
    notes: 'Charge card — balance must be paid in full monthly',
  },

  // ── Card Acquisition Stage ──
  {
    name: 'American Express Blue Business Cash',
    program: 'program_a',
    stage: 'Card Acquisition',
    category: 'funding',
    reports_to: 'Equifax, Experian (business)',
    terms: '0% intro APR 12 months on purchases, 2% cash back up to $50k/year, no annual fee',
    pg_required: 'yes',
    description: 'American Express business card with 12 months 0% APR and 2% cash back. Amex reports to business credit bureaus too.',
    learn_more_url: 'https://www.americanexpress.com/us/credit-cards/business/blue-business-cash/',
    apply_url: 'https://www.americanexpress.com/us/credit-cards/business/blue-business-cash/',
    priority_score: 88,
    is_active: true,
    notes: 'Amex tends to approve higher limits — apply in Card Acquisition phase',
  },
  {
    name: 'American Express Blue Business Plus',
    program: 'program_a',
    stage: 'Card Acquisition',
    category: 'funding',
    reports_to: 'Equifax, Experian (business)',
    terms: '0% intro APR 12 months, 2x Membership Rewards on first $50k, no annual fee',
    pg_required: 'yes',
    description: 'Earns 2x Membership Rewards points instead of cash back. Ideal if client also has an Amex personal card to transfer points.',
    learn_more_url: 'https://www.americanexpress.com/us/credit-cards/business/blue-business-plus/',
    apply_url: 'https://www.americanexpress.com/us/credit-cards/business/blue-business-plus/',
    priority_score: 85,
    is_active: true,
    notes: 'Can apply alongside Blue Business Cash — Amex allows multiple cards',
  },
  {
    name: 'Wells Fargo Business Platinum',
    program: 'program_a',
    stage: 'Card Acquisition',
    category: 'funding',
    reports_to: 'Equifax, Experian (business)',
    terms: '0% intro APR 9 months, choice of cash back or rewards, no annual fee',
    pg_required: 'yes',
    description: 'Solid 0% intro APR card from Wells Fargo. Good for clients who have existing WF banking relationships.',
    learn_more_url: 'https://www.wellsfargo.com/biz/business-credit/credit-cards/business-platinum-credit-card/',
    apply_url: 'https://www.wellsfargo.com/biz/business-credit/credit-cards/business-platinum-credit-card/',
    priority_score: 72,
    is_active: true,
    notes: 'Best for clients with existing Wells Fargo business accounts',
  },

  // ── Optimization Stage ──
  {
    name: 'Nav Business Credit Monitoring',
    program: 'program_a',
    stage: 'Optimization',
    category: 'monitoring',
    reports_to: 'Dun & Bradstreet, Equifax Business, Experian Business',
    terms: '$29.99–$49.99/month',
    pg_required: 'no',
    description: 'Tracks personal and business credit scores across all major bureaus. Alerts for new accounts, utilization changes, and derogatory marks.',
    learn_more_url: 'https://www.nav.com',
    apply_url: 'https://www.nav.com',
    priority_score: 80,
    is_active: true,
    notes: 'Use to monitor utilization across all acquired cards during optimization phase',
  },
]

// ─── Program B — Business Credit Builder ─────────────────────────────────────
const PROGRAM_B: DefaultOpportunity[] = [
  // ── Foundation Stage ──
  {
    name: 'Dun & Bradstreet D-U-N-S Registration',
    program: 'program_b',
    stage: 'Foundation',
    category: 'monitoring',
    reports_to: 'Dun & Bradstreet',
    terms: 'Free',
    pg_required: 'n/a',
    description: 'Register for a free D-U-N-S number — the foundation of business credit. Required before most vendor and net-term accounts will report.',
    learn_more_url: 'https://www.dnb.com/duns-number.html',
    apply_url: 'https://www.dnb.com/duns-number/get-a-duns.html',
    priority_score: 100,
    is_active: true,
    notes: 'Must be completed first — all vendor accounts depend on D-U-N-S existing',
  },
  {
    name: 'Experian Business Credit Profile',
    program: 'program_b',
    stage: 'Foundation',
    category: 'monitoring',
    reports_to: 'Experian Business',
    terms: 'Free to establish',
    pg_required: 'n/a',
    description: 'Set up and monitor your Experian business credit profile. Many lenders use Experian Business to assess creditworthiness.',
    learn_more_url: 'https://www.experian.com/small-business/business-credit-report.jsp',
    apply_url: 'https://www.experian.com/small-business/',
    priority_score: 90,
    is_active: true,
    notes: 'Monitor monthly as accounts are added',
  },
  {
    name: 'Equifax Small Business Credit Monitor',
    program: 'program_b',
    stage: 'Foundation',
    category: 'monitoring',
    reports_to: 'Equifax Business',
    terms: 'Free basic, $14.95/month premium',
    pg_required: 'n/a',
    description: 'Monitor your Equifax business credit file and receive alerts on new reporting activity.',
    learn_more_url: 'https://www.equifax.com/business/products/',
    apply_url: 'https://www.equifax.com/business/products/',
    priority_score: 85,
    is_active: true,
    notes: null,
  },

  // ── Store Credit Stage ──
  {
    name: 'Uline Net 30 Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Uline is one of the most reliable D&B-reporting vendors. Purchase shipping and office supplies to establish net-30 payment history. Order minimum ~$50 recommended.',
    learn_more_url: 'https://www.uline.com',
    apply_url: 'https://www.uline.com',
    priority_score: 98,
    is_active: true,
    notes: 'Place 2-3 orders to get account opened — reporting begins after first invoice',
  },
  {
    name: 'Quill.com Net 30 Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Office supply vendor that reports to D&B. Open an account and purchase office supplies to establish another reporting tradeline.',
    learn_more_url: 'https://www.quill.com',
    apply_url: 'https://www.quill.com',
    priority_score: 93,
    is_active: true,
    notes: null,
  },
  {
    name: 'Grainger Net 30 Account',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30 payment terms',
    pg_required: 'no',
    description: 'Industrial supply company that issues business credit accounts reporting to D&B. Available to businesses in most industries.',
    learn_more_url: 'https://www.grainger.com',
    apply_url: 'https://www.grainger.com/content/account-application',
    priority_score: 88,
    is_active: true,
    notes: 'Best for businesses that can justify industrial/MRO purchases',
  },
  {
    name: 'Amazon Business Prime — Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30, $179/year Prime membership',
    pg_required: 'no',
    description: 'Amazon Business accounts with net-30 payment terms report to D&B. Useful because most businesses already purchase from Amazon regularly.',
    learn_more_url: 'https://business.amazon.com',
    apply_url: 'https://business.amazon.com',
    priority_score: 82,
    is_active: true,
    notes: 'Apply after 2-3 other vendor accounts are established',
  },
  {
    name: 'Summa Office Supplies Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 30, no minimum order',
    pg_required: 'no',
    description: 'Starter-friendly vendor with low order minimums. Reports to both D&B and Experian Business — ideal for building dual-bureau presence early.',
    learn_more_url: 'https://www.summaofficesupplies.com',
    apply_url: 'https://www.summaofficesupplies.com',
    priority_score: 85,
    is_active: true,
    notes: 'Good starter vendor — low barrier to entry',
  },
  {
    name: 'Crown Office Supplies Net 30',
    program: 'program_b',
    stage: 'Store Credit',
    category: 'vendor',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30',
    pg_required: 'no',
    description: 'Another D&B-reporting office supply vendor. Provides an additional tradeline for businesses building their D&B profile.',
    learn_more_url: 'https://www.crownofficesupplies.com',
    apply_url: 'https://www.crownofficesupplies.com',
    priority_score: 78,
    is_active: true,
    notes: null,
  },

  // ── Fleet & Gas Stage ──
  {
    name: 'WEX Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet, Experian Business',
    terms: 'Net 15 or Net 30, accepted at 95%+ gas stations',
    pg_required: 'yes',
    description: 'Fleet fuel card that reports to D&B and Experian Business. Available to businesses with any vehicle or equipment usage. Helps establish payment history beyond vendor accounts.',
    learn_more_url: 'https://www.wexinc.com/solutions/fleet-cards/',
    apply_url: 'https://www.wexinc.com/solutions/fleet-cards/',
    priority_score: 85,
    is_active: true,
    notes: null,
  },
  {
    name: 'Fuelman Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 15, nationwide acceptance',
    pg_required: 'yes',
    description: 'Fleet card accepted at thousands of fueling locations. Reports to D&B. Good alternative or complement to WEX.',
    learn_more_url: 'https://www.fuelman.com',
    apply_url: 'https://www.fuelman.com/apply',
    priority_score: 75,
    is_active: true,
    notes: null,
  },
  {
    name: 'BP Business Solutions Fleet Card',
    program: 'program_b',
    stage: 'Fleet & Gas',
    category: 'fleet',
    reports_to: 'Dun & Bradstreet',
    terms: 'Net 30, BP and Amoco stations',
    pg_required: 'yes',
    description: 'BP fleet card that reports to D&B. Best for clients with operations near BP/Amoco locations.',
    learn_more_url: 'https://www.bpbusinesssolutions.com',
    apply_url: 'https://www.bpbusinesssolutions.com',
    priority_score: 68,
    is_active: true,
    notes: null,
  },

  // ── Cash & Revolving Stage ──
  {
    name: 'Divvy Business Credit Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet, Equifax Business, Experian Business',
    terms: 'No annual fee, reports to 3 business bureaus',
    pg_required: 'no',
    description: 'Charge card / expense management platform that reports to all 3 major business credit bureaus. Great for consolidating spend and getting multi-bureau coverage.',
    learn_more_url: 'https://getdivvy.com',
    apply_url: 'https://getdivvy.com',
    priority_score: 95,
    is_active: true,
    notes: 'Reports to all 3 business bureaus — high value for PAYDEX building',
  },
  {
    name: 'Ramp Business Credit Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet',
    terms: 'No personal guarantee, 1.5% cash back, no fees',
    pg_required: 'no',
    description: 'Corporate card with no personal guarantee for qualifying businesses. Requires $25K+ in business bank account. 1.5% cash back. Reports to D&B.',
    learn_more_url: 'https://ramp.com',
    apply_url: 'https://ramp.com',
    priority_score: 88,
    is_active: true,
    notes: 'Best for clients with strong business banking — no PG is a major advantage',
  },
  {
    name: 'Brex Business Card',
    program: 'program_b',
    stage: 'Cash & Revolving',
    category: 'cash',
    reports_to: 'Dun & Bradstreet',
    terms: 'No personal guarantee, high limits, no annual fee',
    pg_required: 'no',
    description: 'Corporate card designed for startups and growing businesses. No personal guarantee. Requires Brex Cash account or $10K+ monthly deposits.',
    learn_more_url: 'https://www.brex.com',
    apply_url: 'https://www.brex.com',
    priority_score: 82,
    is_active: true,
    notes: null,
  },
]

// ─── Program C — Capital Monitoring Membership ────────────────────────────────
const PROGRAM_C: DefaultOpportunity[] = [
  {
    name: 'Nav Business Credit Monitoring (Premium)',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'monitoring',
    reports_to: 'Dun & Bradstreet, Equifax Business, Experian Business',
    terms: '$49.99/month',
    pg_required: 'no',
    description: 'Full monitoring of business and personal credit across all bureaus. Includes D&B PAYDEX, Experian Intelliscore, and personal FICO tracking. Used in monthly capital readiness snapshots.',
    learn_more_url: 'https://www.nav.com',
    apply_url: 'https://www.nav.com',
    priority_score: 95,
    is_active: true,
    notes: 'Primary monitoring tool for Program C monthly review cycle',
  },
  {
    name: 'CreditSafe Business Monitor',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'monitoring',
    reports_to: 'Equifax Business, Experian Business',
    terms: 'Custom pricing, contact for quote',
    pg_required: 'no',
    description: 'Enterprise-grade business credit monitoring platform. Provides real-time alerts, scoring breakdowns, and lender risk models. Used to assess capital access potential.',
    learn_more_url: 'https://www.creditsafe.com/us/',
    apply_url: 'https://www.creditsafe.com/us/',
    priority_score: 80,
    is_active: true,
    notes: null,
  },
  {
    name: 'Fundbox Line of Credit',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'funding',
    reports_to: 'Dun & Bradstreet',
    terms: 'Up to $150K revolving LOC, weekly repayment, 12-24 week terms',
    pg_required: 'yes',
    description: 'Revolving business line of credit for businesses with 6+ months of revenue history. Soft pull for qualification. Funded in 1-3 days.',
    learn_more_url: 'https://fundbox.com',
    apply_url: 'https://fundbox.com',
    priority_score: 82,
    is_active: true,
    notes: 'Recommend when client meets $50K+ monthly revenue threshold',
  },
  {
    name: 'Bluevine Business Line of Credit',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'funding',
    reports_to: 'Equifax Business',
    terms: 'Up to $250K revolving LOC, 6 or 12 month terms',
    pg_required: 'yes',
    description: 'Flexible revolving line of credit for established businesses. Requires $40K/month revenue. Funded fast. Good capital readiness benchmark target.',
    learn_more_url: 'https://www.bluevine.com',
    apply_url: 'https://www.bluevine.com',
    priority_score: 85,
    is_active: true,
    notes: 'Include in capital readiness scoring when client hits revenue benchmarks',
  },
  {
    name: 'Kabbage (American Express Business Blueprint)',
    program: 'program_c',
    stage: 'Monthly Review',
    category: 'funding',
    reports_to: 'Equifax Business',
    terms: 'Up to $250K LOC, 6, 12, or 18 month terms',
    pg_required: 'yes',
    description: 'Revolving credit line now under American Express. Known for flexible qualification criteria. Good for businesses with consistent revenue but mixed credit.',
    learn_more_url: 'https://www.americanexpress.com/en-us/business/blueprint/',
    apply_url: 'https://www.americanexpress.com/en-us/business/blueprint/',
    priority_score: 78,
    is_active: true,
    notes: null,
  },
]

export const DEFAULT_OPPORTUNITIES: DefaultOpportunity[] = [
  ...PROGRAM_A,
  ...PROGRAM_B,
  ...PROGRAM_C,
]
